set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/vardhan/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/vardhan/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/openlane/pes_vedic_mul"
set ::env(DESIGN_NAME) "pes_vedic_mul"
set ::env(VERILOG_FILES) "/openlane/openlane/pes_vedic_mul/src/pes_vedic_mul.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10.0"
set ::env(DESIGN_IS_CORE) "1"
set ::env(CORE_AREA) "5.52 10.88 81.88 87.04"
set ::env(CORE_HEIGHT) "76.16"
set ::env(CORE_WIDTH) "76.36"
set ::env(DIE_AREA) "0.0 0.0 87.495 98.215"
set ::env(FP_ASPECT_RATIO) "1"
set ::env(FP_CORE_UTIL) "50"
set ::env(SYNTH_STRATEGY) "AREA 0"
set ::env(SYNTH_TIMING_DERATE) "0.05"
